use_small_heuristics = "Max"
fn_params_layout = "Compressed"
hard_tabs = true
use_field_init_shorthand = true
max_width = 100
match_block_trailing_comma = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
comment_width = 100
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
